#!/bin/bash

# Vars
config_home="${XDG_CONFIG_HOME:-$HOME/.config}"

# Functions
is_laptop() {
    [ "$(uname -n)" == 'Renda' ]
}

# Background applications
dunst -conf "$config_home/openbox/dunstrc" &
lxqt-policykit-agent &
nm-applet &
opensnap -d &
picom -b &
redshift &
tint2 -c "$config_home/openbox/tint2rc" &
volumeicon &
(is_laptop || discord --start-minimized) &
(is_laptop || steam -silent) &

# Other stuff
mpc clear && mpc load main && mpc shuffle
setxkbmap -option "shift:both_capslock"
xset -b
~/.fehbg
