#!/bin/bash

# Vars
config_home="${XDG_CONFIG_HOME:-$HOME/.config}"

# Functions
is_laptop() {
    [ "$(uname -n)" == 'Renda' ]
}

set_gtk_setting() {
    gtk3_ini="$config_home/gtk-3.0/settings.ini"
    value="$(grep "$1" "$gtk3_ini" | awk -F= '{print $2}')"
    gsettings set org.gnome.desktop.interface "$1" "$value"
}

# Increase scaling on laptop
is_laptop && wlr-randr --output eDP-1 --preferred --scale 1.2

# Ensure GTK uses the correct theme settings
set_gtk_setting cursor-theme
set_gtk_setting font-name
set_gtk_setting gtk-theme
set_gtk_setting icon-theme

# Background applications
dunst -conf "$config_home/labwc/dunstrc" &
gammastep &
lxqt-policykit-agent  &
swaybg -i /usr/share/backgrounds/wallpaper.jpg -m stretch &

# Taskbar
sfwbar -f "$config_home/labwc/sfwbar.config" &
nm-applet --indicator &
(is_laptop && cbatticon) &

# Other stuff
mpc clear && mpc load main && mpc shuffle
