#!/bin/bash
[ -n "${LABWC_SKIP_AUTOSTART:-}" ] && return

# Vars
config_home="${XDG_CONFIG_HOME:-$HOME/.config}"

# Functions
is_laptop() {
    [ "$(uname -n)" == 'Renda' ]
}

set_gtk_setting() {
    gtk3_ini="$config_home/gtk-3.0/settings.ini"
    value="$(grep "$1" "$gtk3_ini" | awk -F= '{print $2}')"
    gsettings set org.gnome.desktop.interface "$1" "$value"
}

wait_start() {
    sleep 2
    "$@"
}

# Increase scaling on laptop
is_laptop && wlr-randr --output eDP-1 --preferred --scale 1.2

# Ensure GTK uses the correct theme settings
set_gtk_setting cursor-theme
set_gtk_setting font-name
set_gtk_setting gtk-theme
set_gtk_setting icon-theme

# Start systemd services
systemctl --user start labwc-session.target

# I don't want to wrap these into Systemd services
swaybg -i /usr/share/backgrounds/wallpaper.jpg -m stretch &
is_laptop || wait_start discord --start-minimized &
is_laptop || wait_start steam -silent &
{ mpc clear && mpc load main && mpc shuffle; } &
