#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

xset -b        &
lxqt-policykit-agent &
volumeicon &
nm-applet  &
cbatticon  &

mpc clear
mpc load main
mpc shuffle

(sleep 1s && ~/.fehbg) &
(sleep 1s && setxkbmap -option "shift:both_capslock") &

exec fluxbox
