complete -c dsda-doom -f -l help -d "Print out command line argument information."
complete -c dsda-doom -f -o help -d "Print out command line argument information."
complete -c dsda-doom -r -o iwad -d "Load the given iwad file."
complete -c dsda-doom -r -o file -d "Load additional wad files."
complete -c dsda-doom -r -o deh -d "Load additional deh files."
complete -c dsda-doom -r -o bex -d "Load additional deh files."
complete -c dsda-doom -r -o playdemo -d "Play the given demo file."
complete -c dsda-doom -r -o playlump -d "Play the given internal demo lump."
complete -c dsda-doom -r -o timedemo -d "Play the given demo file as fast as possible, timing the process."
complete -c dsda-doom -r -o fastdemo -d "Play the given demo file as fast as possible, skipping some frames."
complete -c dsda-doom -r -o record -d "Record a demo to the given file."
complete -c dsda-doom -r -o recordfromto -d "Play back the first file while writing to the second."
complete -c dsda-doom -r -o from_key_frame -d "Restore state and demo buffer from a key frame file."
complete -c dsda-doom -x -o warp -d "War to the given episode and / or map."
complete -c dsda-doom -x -o skill -d "Set the skill level." -a "0 1 2 3 4 5"
complete -c dsda-doom -f -o uv -d "Set the skill level to 4."
complete -c dsda-doom -f -o nm -d "Set the skill level to 5."
complete -c dsda-doom -x -o episode -d "Warp to the first map in the given episode."
complete -c dsda-doom -x -o complevel -d "Set the compatibility level."
complete -c dsda-doom -x -o cl -d "Set the compatibility level."
complete -c dsda-doom -f -o fast -d "Enable fast monsters."
complete -c dsda-doom -f -o respawn -d "Enable monster respawning."
complete -c dsda-doom -f -o nomonsters -d "Disable monster spawning."
complete -c dsda-doom -f -o nomo -d "Disable monster spawning."
complete -c dsda-doom -f -o longtics -d "Enable high precision turn angles."
complete -c dsda-doom -f -o shorttics -d "Restrict turn angles to lower precision."
complete -c dsda-doom -f -o heretic -d "Set the game to heretic."
complete -c dsda-doom -f -o hexen -d "Set the game to hexen."
complete -c dsda-doom -x -o class -d "Set the player class in hexen."
complete -c dsda-doom -f -o randclass -d "Set a random player class in hexen deathmatch."
complete -c dsda-doom -f -o dsdademo -d "Enable extended demo format."
complete -c dsda-doom -f -o solo-net -d "Play a net game with one player."
complete -c dsda-doom -f -o coop_spawns -d "Play single player with coop thing spawns."
complete -c dsda-doom -f -o pistolstart -d "Automatically pistol start each map."
complete -c dsda-doom -f -o wandstart -d "Automatically pistol start each map."
complete -c dsda-doom -f -o chain_episodes -d "Completing one episode leads to the next without interruption."
complete -c dsda-doom -f -o stroller -d "Apply stroller category limitations."
complete -c dsda-doom -x -o turbo -d "Set player speed percent."
complete -c dsda-doom -x -o game_speed -d "Sets game speed percent."
complete -c dsda-doom -f -o tas -d "Lift strict mode restrictions."
complete -c dsda-doom -f -o build -d "Start in build mode."
complete -c dsda-doom -f -o quit_after_brute_force -d "Quit the game when brute force ends."
complete -c dsda-doom -x -o first_input -d "Build the first frame F S T."
complete -c dsda-doom -x -o command -d "Run a console command."
complete -c dsda-doom -x -o skipsec -d "Skip to the given time (mm:ss or ss) - negative times seek from the end."
complete -c dsda-doom -x -o skiptic -d "Skip to the given tic - negative tics seek from the end."
complete -c dsda-doom -f -o track_pacifist -d "Track pacifist category restrictions."
complete -c dsda-doom -f -o track_100k -d "Track when 100% kills is reached."
complete -c dsda-doom -f -o track_reality -d "Track reality and almost reality categories restrictions."
complete -c dsda-doom -x -o time_keys -d "Announce the time when keys are picked up."
complete -c dsda-doom -x -o time_use -d "Announce the time when the use command is activated."
complete -c dsda-doom -x -o time_secrets -d "Announce the time when a secret is collected."
complete -c dsda-doom -x -o time_all -d "Announce the time when any -time_* event happens."
complete -c dsda-doom -f -o track_player -d "Add player info to the tracker."
complete -c dsda-doom -x -o track_line -d "Add at least one line to the tracker."
complete -c dsda-doom -x -o track_line_distance -d "Add at least one line distance to the tracker."
complete -c dsda-doom -x -o track_sector -d "Add at least one sector to the tracker."
complete -c dsda-doom -x -o track_mobj -d "Add at least one mobj to the tracker."
complete -c dsda-doom -x -o assign -d "Temporarily assign config variables."
complete -c dsda-doom -x -o update -d "Permanently update config variables."
complete -c dsda-doom -f -o analysis -d "Write various data to analysis.txt."
complete -c dsda-doom -f -o levelstat -d "Write level stats to levelstat.txt."
complete -c dsda-doom -f -o export_text_file -d "Export a dsda-format text file template."
complete -c dsda-doom -r -o track_playback -d "Treat demo playback as an attempt for the given split file base."
complete -c dsda-doom -r -o export_ghost -d "Export a ghost file."
complete -c dsda-doom -r -o import_ghost -d "Import at least one ghost file."
complete -c dsda-doom -x -o consoleplayer -d "Set the console player."
complete -c dsda-doom -x -o spechit -d "Set a magic spechit base address for certain overrun demos."
complete -c dsda-doom -x -o setmem -d "Set a magic block of memory for certain overrun demos."
complete -c dsda-doom -r -o data -d "Set the data directory."
complete -c dsda-doom -r -o save -d "Set the save directory."
complete -c dsda-doom -r -o config -d "Set the config file."
complete -c dsda-doom -r -o hud -d "Set the hud config file."
complete -c dsda-doom -r -o shotdir -d "Set the screenshot directory."
complete -c dsda-doom -x -o movie -d "Set the target final level for movie demos."
complete -c dsda-doom -r -o viddump -d "Dump a video to the chosen file name."
complete -c dsda-doom -r -o dehout -d "Set dehacked log file."
complete -c dsda-doom -r -o bexout -d "Set dehacked log file."
complete -c dsda-doom -f -o verbose -d "Enable all logging."
complete -c dsda-doom -f -o quiet -d "Disable all logging."
complete -c dsda-doom -f -o v -d "Print the version and exit."
complete -c dsda-doom -f -o resetgamma -d "Reset gamma and exit."
complete -c dsda-doom -f -o force_old_zdoom_nodes -d "Force extended (non-gl) zdoom nodes."
complete -c dsda-doom -f -o sigsegv -d "Disable the SIGSEGV signal handler."
complete -c dsda-doom -f -o deathmatch -d "Enable deathmatch mode."
complete -c dsda-doom -f -o altdeath -d "Enable altdeath mode."
complete -c dsda-doom -x -o timer -d "Set the level time limit (in minutes) for deathmatch."
complete -c dsda-doom -x -o frags -d "Set the level frag limit for deathmatch."
complete -c dsda-doom -f -o nosound -d "Disable sound."
complete -c dsda-doom -f -o nomusic -d "Disable music."
complete -c dsda-doom -f -o nosfx -d "Disable sfx."
complete -c dsda-doom -f -o nodraw -d "Disable drawing."
complete -c dsda-doom -f -o nodeh -d "Skip dehacked lumps inside wads."
complete -c dsda-doom -f -o nomapinfo -d "Skip *MAPINFO lumps."
complete -c dsda-doom -f -o noautoload -d "Ignore autoload files."
complete -c dsda-doom -f -o noload -d "Ignore autoload files."
complete -c dsda-doom -f -o nocheats -d "Ignore dehacked cheats."
complete -c dsda-doom -f -o nojoy -d "Disable joystick input."
complete -c dsda-doom -f -o nomouse -d "Disable mouse input."
complete -c dsda-doom -f -o no_message_box -d "Disable message boxes."
complete -c dsda-doom -f -o fullscreen -d "Temporarily turn on fullscreen mode."
complete -c dsda-doom -f -o window -d "Temporarily turn on windowed mode."
complete -c dsda-doom -x -o width -d "Temporarily set the resolution width."
complete -c dsda-doom -x -o height -d "Temporarily set the resolution height."
complete -c dsda-doom -x -o geometry -d "Temporarily set the resolution WxH[w|f]."
complete -c dsda-doom -x -o geom -d "Temporarily set the resolution WxH[w|f]."
complete -c dsda-doom -x -o vidmode -d "Temporarily set the graphics renderer (sw or gl)." -a "sw gl"
complete -c dsda-doom -x -o aspect -d "Set the fov aspect ratio WxH."
complete -c dsda-doom -x -o emulate -d "Emulate errors from a version of prboom+ (a.b.c.d)."
complete -c dsda-doom -f -o doom95 -d "Use doom95's adjacent sector limit."
complete -c dsda-doom -f -o blockmap -d "Rebuild the blockmap (ignore BLOCKMAP lump)."
complete -c dsda-doom -f -o force_monster_avoid_hazards -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o force_remove_slime_trails -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o force_no_dropoff -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o force_truncated_sector_specials -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o force_boom_brainawake -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o force_prboom_friction -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o reject_pad_with_ff -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o force_lxdoom_demo_compatibility -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o allow_ssg_direct -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o treat_no_clipping_things_as_not_blocking -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o force_incorrect_processing_of_respawn_frame_entry -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o force_correct_code_for_3_keys_doors_in_mbf -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o uninitialize_crush_field_for_stairs -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o force_boom_findnexthighestfloor -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o allow_sky_transfer_in_boom -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o apply_green_armor_class_to_armor_bonuses -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o apply_blue_armor_class_to_megasphere -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o force_incorrect_bobbing_in_boom -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o boom_deh_parser -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o mbf_remove_thinker_in_killmobj -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o do_not_inherit_friendlyness_flag_on_spawn -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o do_not_use_misc12_frame_parameters_in_a_mushroom -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o apply_mbf_codepointers_to_any_complevel -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o reset_monsterspawner_params_after_loading -d "Special flag to fix sync errors in some demos."
complete -c dsda-doom -f -o debug_mapinfo -d "Enable MAPINFO parsing in Doom."
