complete -c woof -o 1 -f -d "Display window at 1x scale. Implies -window."
complete -c woof -o 2 -f -d "Display window at 2x scale. Implies -window."
complete -c woof -o 3 -f -d "Display window at 3x scale. Implies -window."
complete -c woof -o altdeath -f -d "Altdeath mode. Weapons and items respawn."
complete -c woof -o autojoin -f -d "Automatically join LAN multiplayer server."
complete -c woof -o avg -f -d "End deathmatch levels after 20 minutes."
complete -c woof -o beta -f -d "Press beta emulation mode (complevel mbf only)."
complete -c woof -o bex -r -d "Load DeHackEd / BEX patches."
complete -c woof -o bexout -r -d "Enable verbose DeHackEd parser logging."
complete -c woof -o blockmap -f -d "Force rebuild BLOCKMAP."
complete -c woof -o bsp -f -d "Force rebuild nodes."
complete -c woof -o cl -x -a "vanilla boom mbf mbf21" -d "Emulate a specific version of Doom."
complete -c woof -o complevel -x -a "vanilla boom mbf mbf21" -d "Emulate a specific version of Doom."
complete -c woof -o config -r -d "Load config from file."
complete -c woof -o connect -x -d "Connect to the given server address."
complete -c woof -o coop_spawns -f -d "Start single player game with multiplayer item spawns."
complete -c woof -o deathmatch -f -d "Start a deathmatch game."
complete -c woof -o dedicated -f -d "Start a dedicated server."
complete -c woof -o deh -r -d "Load DeHackEd / BEX patches."
complete -c woof -o dehout -r -d "Enable verbose DeHackEd parser logging."
complete -c woof -o devparm -f -d "Enable developer mode."
complete -c woof -o dm3 -f -d "Deathmatch 3.0. Weapons stay, items respawn."
complete -c woof -o dog -f -d "Enable a single helper dog."
complete -c woof -o dogs -x -d "Enable the given number of helper dogs."
complete -c woof -o dumptranmap -r -d "Dump TRANMAP lump"
complete -c woof -o dup -x -d "Reduce network tic resolution."
complete -c woof -o episode -x -d "Start playing on a given episode."
complete -c woof -o extratics -x -d "Send extra tics per network packet."
complete -c woof -o fast -f -d "Enable fast monsters."
complete -c woof -o fastdemo -r -d "Play a demo as fast as possible."
complete -c woof -o file -r -d "Load WAD files." -a "(ls $DOOMWADDIR)"
complete -c woof -o force_old_zdoom_nodes -f -d "Force extended (non-GL) ZDoom nodes."
complete -c woof -o frags -x -d "End deathmatch level after a given number of frags."
complete -c woof -o fullscreen -f -d "Run in fullscreen mode."
complete -c woof -o gameversion -x -a "1.9 ultimate final chex" -d "Emulate a specific version of vanilla Doom."
complete -c woof -o help -f -d "Print command line help."
complete -c woof -o iwad -r -d "Use specified IWAD file."
complete -c woof -o left -f -d "Run as left screen in three-screen mode."
complete -c woof -o levelstat -f -d "Write level statistics to levelstat.txt."
complete -c woof -o loadgame -x -d "Load given savegame number."
complete -c woof -o longtics -f -d "Record longtics demo."
complete -c woof -o maxdemo -x -d "Set demo buffer size (KiB)."
complete -c woof -o nm -f -d "Nightmare difficulty (Skill 5)."
complete -c woof -o noautoload -f -d "Disable autoload of .wad and .deh files."
complete -c woof -o noblit -f -d "Disable screen blitting."
complete -c woof -o nocheats -f -d "Ignore custom cheats in DeHackEd lumps."
complete -c woof -o nodeh -f -d "Disable loading embedded DeHackEd lumps."
complete -c woof -o nodes -x -d "Start game when the given number of cliens have connected."
complete -c woof -o nodraw -f -d "Disable rendering entirely."
complete -c woof -o noextras -f -d "Disable autoload of extras.wad."
complete -c woof -o nograbmouse -f -d "Don't grab mouse in windowed mode."
complete -c woof -o nogui -f -d "Don't show dialog boxes on errors."
complete -c woof -o nomapinfo -f -d "Disable UMAPINFO loading."
complete -c woof -o nomo -f -d "Disable monsters."
complete -c woof -o nomonsters -f -d "Disable monsters."
complete -c woof -o nomusic -f -d "Disable music."
complete -c woof -o nooptions -f -d "Disable loading embedded OPTIONS lumps."
complete -c woof -o nosfx -f -d "Disable sound effects."
complete -c woof -o nosound -f -d "Disable all sound."
complete -c woof -o nouncapped -f -d "Disable uncapped framerate."
complete -c woof -o oldsync -f -d "Use old network sync code."
complete -c woof -o pistolstart -f -d "Enable automatic pistol start."
complete -c woof -o playdemo -r -d "Play back a demo."
complete -c woof -o port -x -d "Use specified port for communications."
complete -c woof -o privateserver -f -d "Start a private server."
complete -c woof -o quiet -f -d "Print debug info with minimum verbosity."
complete -c woof -o record -r -d "Record a demo."
complete -c woof -o recordfrom -r -d "Record a demo from the given save slot."
complete -c woof -o recordfromto -r -d "Record over a demo."
complete -c woof -o respawn -f -d "Enable respawning monsters."
complete -c woof -o right -f -d "Run as right screen in three-screen mode."
complete -c woof -o save -r -d "Use alternate save directory."
complete -c woof -o server -f -d "Start a multiplayer server."
complete -c woof -o servername -x -d "Specify server name."
complete -c woof -o setmem -x -a "dos622 dos71 dosbox" -d "Emulate a specific DOS version upon NULL dereference."
complete -c woof -o shorttics -f -d "Use low mouse resolution."
complete -c woof -o shotdir -r -d "Use alternate screenshot directory."
complete -c woof -o skill -x -a "0 1 2 3 4 5" -d "Set game skill."
complete -c woof -o skipsec -x -d "Skip to the given time in a demo."
complete -c woof -o solo-net -f -d "Simulate a one-player network game."
complete -c woof -o spechit -x -d "Specify magic value for spechit overrun emulation."
complete -c woof -o speed -x -d "Set game speed percentage."
complete -c woof -o statdump -r -d "Dump statistics information."
complete -c woof -o strict -f -d "Use strict DSDA setting."
complete -c woof -o timedemo -r -d "Play demo and measure framerate."
complete -c woof -o timer -x -d "End level after the given number of minutes."
complete -c woof -o tranmap -f -d "Force rebuild TRANMAP lump."
complete -c woof -o turbo -x -d "Set player speed multiplier."
complete -c woof -o uncapped -f -d "Enable uncapped framerate."
complete -c woof -o uv -f -d "Ultra Violence difficulty (Skill 4)."
complete -c woof -o verbose -f -d "Print debug info with maximum verbosity."
complete -c woof -o version -f -d "Print program version and exit."
complete -c woof -o warp -x -d "Warp to the given level."
complete -c woof -o window -f -d "Run in windowed mode."
