#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

xset -b        &
lxqt-policykit-agent &
volumeicon &
nm-applet  &
xremap /etc/xremap/default.yml --watch &

mpc clear
mpc load Main
mpc shuffle

(sleep 1s && ~/.fehbg) &
(sleep 1s && steam -silent) &
(sleep 1s && discord --start-minimized) &
(sleep 1s && setxkbmap -option "shift:both_capslock") &

exec fluxbox
